### ISSUE TITLE
Integration stops working in 2023.05 due to async issue

### ISSUE THREAD

**Issue by ThatTallGuy21** [daviswieck/ha-college-football#6]
This integration is no longer working due to an async issue. Below is the log. I was experiencing the same exact issue with the ha-nfl integration until today when they pushed an async fix. The same issue exists for the ha-nhl integration as well. 

Note: I'm on HA 2023.5.2
- Supervisor 2023.04.1
- Operating System 10.1
- Frontend 20230503.3 - latest

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/college_football/__init__.py:66
Integration: College Football (documentation, issues)
First occurred: 9:34:32 PM (1 occurrences)
Last logged: 9:34:32 PM

Error setting up entry College_Football for college_football
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/college_football/__init__.py", line 66, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by ThatTallGuy21** [comment]
Issue can be fixed by replacing line 66 in init.pi

hass.config_entries.async_setup_platforms(entry, PLATFORMS)

replace with

await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)

**Comment by daviswieck** [comment]
Fixed in release V1.02

Thansk!
